### ISSUE TITLE
Error while execute the script

### ISSUE THREAD

**Issue by cafeitduong** [UnkL4b/GitMiner#23]
Hello,

Thanks for releasing new version, the older one is not working recently.
However, I've followed the installation guideline with below steps:

1. Git clone the latest repos
2. Update the requirement.txt with (lxml, requests, argparse, json, re), looks like it's missing in code
3. pip3 install -r requirements
4. Execute the sample command: python3 gitminer-v2.0.py -q 'filename:wp-config extension:php FTP_HOST in:file ' -m wordpress -c <my_cookies>
5 Got below error message: 
`Traceback (most recent call last):
  File "gitminer-v2.0.py", line 11, in <module>
    from core.Parser import Parser
  File "/home/scumblr/GitMiner/core/Parser.py", line 6, in <module>
    from core.sendRequest import requestPage
  File "/home/scumblr/GitMiner/core/sendRequest.py", line 3, in <module>
    from core import Parser
ImportError: cannot import name 'Parser'
`

Please help me, am I missing something?

Thanks.

**Comment by danilovazb** [comment]
Hi, please, remove and clone again

**Comment by danilovazb** [comment]
what is your OS?

**Comment by cafeitduong** [comment]
It is: Ubuntu 14.04.3 LTS (GNU/Linux 3.19.0-25-generic x86_64)

**Comment by icxcoffee** [comment]
Me too,My OS is centos_7.

**Comment by icxcoffee** [comment]
This problem may be caused by python34. When I use python35, there is no such problem.

**Comment by icxcoffee** [comment]
Python27 also has this problem.

**Comment by icxcoffee** [comment]
Using python27 also has this problem.

**Comment by cafeitduong** [comment]
I see let me try to use python35. Thanks!

**Comment by tanphamit4vn** [comment]
Hi All,
I have no problem with **Ubuntu 16.04**  with below python version and pip.

 `apt install python3.5 `
` apt install python3-pip `
Git Clone GitMiner and run install follow the guideline.

Hope this will help.
Thanks
