### ISSUE TITLE
执行命令时出现问题

### ISSUE THREAD

**Issue by dahan168** [UnkL4b/GitMiner#25]
Traceback (most recent call last):
  File "gitminer-v2.0.py", line 67, in <module>
    GitMiner().start()
  File "gitminer-v2.0.py", line 39, in __init__
    self.cookie = headers.parseCookie(self.args.cookie)
  File "/root/GitMiner/config/headers.py", line 29, in parseCookie
    values = line.strip().split("=")[1]
IndexError: list index out of range
请问这是出了什么问题

**Comment by danilovazb** [comment]
您需要像示例中那样放置完整的cookie。
