### ISSUE TITLE
What do I put in the --cookie paramter?

### ISSUE THREAD

**Issue by zix3r** [UnkL4b/GitMiner#26]
What do I put in it? I just don't know, Send me a picture or just describe it specificly where I can get it.

**Comment by syrius01** [comment]
I'm always getting this error msg:

Traceback (most recent call last):
  File "gitminer.py", line 67, in <module>
    GitMiner().start()
  File "gitminer.py", line 39, in __init__
    self.cookie = headers.parseCookie(self.args.cookie)
  File "/home/syrius/GitMiner/GitMiner/config/headers.py", line 29, in parseCookie
    values = line.strip().split("=")[1]
IndexError: list index out of range
root@kalib0x:/home/syrius/GitMiner/GitMiner# python3 gitminer.py -q filename:some_files -o test1-output.txt -c h8h....(cookie)

**Comment by 0xxk** [comment]
After copying the data in the cookie, it prompts: OSError: [Errno 36] Filename too long. Why is this happening? Thank you!
![1576753933(1)](https://user-images.githubusercontent.com/53210921/71169301-9abf8100-2293-11ea-8c43-fec275744b3b.jpg)
