### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by zq110119** [UnkL4b/GitMiner#28]
[root@202-39-176-98 GitMiner]# python gitminer-v2.0.py --query 'filename:configuration extension:php "public password" in:file' -m joomla -c pAAAhPOma9jEsXyLWZ-16RTTsGI8wDawbNs4
Traceback (most recent call last):
  File "gitminer-v2.0.py", line 67, in <module>
    GitMiner().start()
  File "gitminer-v2.0.py", line 39, in __init__
    self.cookie = headers.parseCookie(self.args.cookie)
  File "/tmp/GitMiner/config/headers.py", line 29, in parseCookie
    values = line.strip().split("=")[1]
IndexError: list index out of range

**Comment by danilovazb** [comment]
set full cookie, like help desc....

python3 gitminer-v2.0.py --help
